name: 'Translate'
description: 'Automatic translation using GPT'
inputs:
  folder-to-translate:  # id of input
    description: 'Path to folder to translate'
    required: true
    default: 'docs/'
  language:  # id of input
    description: 'Language to translate to'
    required: true
    default: 'es'
  output-folder:
    description: "Output Folder"
    default: 'docs_translated/'
  max-chunk-tokens:
    description: "Max size of chunk to translate at once"
    default: "1000"
  config-folder:
    description: "Config Folder"
    default: './configs'
outputs:
  translated-files:
    description: 'Translated files'
    value: ${{ steps.changed-files.outputs.changed_files }} 

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      run: |
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.md$' | xargs)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install gpt-translate
      shell: bash
    - name: translating files
      run: |
        gpt_translate.files ${{ steps.changed-files.outputs.changed_files }} \
          --input_folder ${{ inputs.folder-to-translate }} \
          --out_folder ${{ inputs.output-folder }} \
          --language ${{ inputs.language }} \
          --max_chunk_tokens ${{ inputs.max-chunk-tokens }} \
          --config_folder ${{ inputs.config-folder }} \
          --replace
      shell: bash