Logs:
  debug: false  # Debug mode
  weave_project: "gpt-translate"  # Weave project
  silence_openai: true  # Silence OpenAI logger

Translation:
  language: "ja"  # Language to translate to
  config_folder: "./configs_dev"  # Config folder
  replace: true  # Replace existing file
  remove_comments: true  # Remove comments
  do_evaluation: true  # Do evaluation
  max_openai_concurrent_calls: 7  # Max number of concurrent calls to OpenAI
  max_chunk_tokens: 3600  # Max number of tokens in a chunk

Files:
  input_file: "docs/intro.md"  # File to translate
  out_file: " intro_ja.md"  # File to save the translated file to
  input_folder: null  # Folder to translate
  out_folder: null  # Folder to save the translated files to
  limit: null  # Limit number of files to translate

Model:
  model: "gpt-4o"
  temperature: 1.0
